export const TOKEN_ERROR_CODES = {
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
} as const;

export const TOKEN_MESSAGES = {
  INVALID_REFRESH_TOKEN: "Invalid refresh token.",
  REFRESH_TOKEN_EXPIRED: "Refresh token expired.",
  ACCESS_TOKEN_EXPIRED: "Access token expired.",
  INVALID_ACCESS_TOKEN: "Invalid access token.",
} as const;
